### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by johnathan-horner** [safak/youtube23#28]
receiving this message after running vite build index-30b14e19.js:3601 Error: Could not load potsdamer-platz/potsdamer_platz_1k.hdr: Failed to fetch)
    at Object.onError (index-30b14e19.js:3605:23539)
    at index-30b14e19.js:3571:185177
by @ index-30b14e19.js:3601

**Comment by devwander** [comment]
I ran into the same error, from what I found it's something to do with using the 3ds models (I didn't dig too deep), but it was resolved by running an `npm update` updating the project's libraries.
